import React from 'react';
import type { Equation, Grade, Operation } from '../utils/equationGenerator';
import EquationCard from './EquationCard';

interface WorksheetProps {
  equations: Equation[];
  grade: Grade;
  operation: Operation;
}

const Worksheet: React.FC<WorksheetProps> = ({ equations, grade, operation }) => {
  const date = new Date().toLocaleDateString();

  return (
    <div className="worksheet printable-area">
      <div className="worksheet-header">
        <div className="student-info">
          <div><strong>Name:</strong> ___________________________</div>
          <div><strong>Date:</strong> {date}</div>
        </div>
        <div className="title-info">
          <h2>{grade} Math Practice</h2>
          <p>{operation} Worksheet</p>
        </div>
      </div>

      <div className="equation-grid">
        {equations.map((eq) => (
          <EquationCard key={eq.id} equation={eq} />
        ))}
      </div>

      <footer className="worksheet-footer">
        Generated by MathGen Kids
      </footer>
    </div>
  );
};

export default Worksheet;
